views: # NEVER REMOVE THIS LINE

  # Default views (you can edit them!)

  # ================================================================================================================================================================
  # 这是主页
  # Home
  home:
    title: 主页
    show_in_navbar: true
    show_in_menu: false
    show_in_favorites: false
    icon: mdi:home
    addons:
      #      welcome_message:
      #        - title: hide
      favorites:
        - title: Favorites
          show_title: true
          columns: 3
      menu:
        - title: Menu

  # 这是导航菜单页
  # Menu
  menu:
    title: 导航菜单
    show_in_navbar: true
    show_in_menu: true
    show_in_favorites: false
    subtitle: "[[[ return `HKI 5 v.${states['sensor.hki_current_version'].state} - 导航菜单页`; ]]]"
    icon: mdi:apps
    addons:
      favorites:
        - title: Favorites
      menu:
        - title: Menu

  # Add your own views below this line!

  # ================================================================================================================================================================
  # Lights库 这是灯光库 一些灯的聚集地 灯光控制
  # ===================================================
  # subtitle: "[[[ if (states['sensor.current_lights_on'].state == 0) return `All lights are turned off`; if (states['sensor.current_lights_on'].state == 1) return `1 light is turned on`; else return `${states['sensor.current_lights_on'].state} lights are turned on`; ]]]"
  # ===================================================
  # type: color-temp | rgb | cover | switch | graph
  # ===================================================
  # Lights (example)
  lights:
    title: 灯光控制
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: true
    subtitle: "[[[ if (states['sensor.current_lights_on'].state == 0) return `灯均已关闭。`;
    if (states['sensor.current_lights_on'].state == 1) return `有一盏灯打开。`;
    else return `当前有 ${states['sensor.current_lights_on'].state} 盏灯开启。`; ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:lightbulb-group-outline
    button_badge: sensor.current_lights_on
    button_label: "[[[ if (states['sensor.current_lights_on'].state == 0) return `灯均已关闭`; else return `有${states['sensor.current_lights_on'].state} 盏灯打开`; ]]]"
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    addons:
      button:
        - title: 厨房
          entities:
            - entity: switch.212a01_cloud_873391
              type: cover
        - title: 客厅
          entities:
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
        - title: 餐厅
          entities:
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
        - title: 门厅&过道
          entities:
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
            - entity: switch.212a01_cloud_873391
        - title: 主卧
          entities:
            - entity: switch.212a01_cloud_873391
        - title: 次卧
          entities:
            - entity: switch.212a01_cloud_873391
        - title: 儿童房台灯
          entities:
            - entity: switch.212a01_cloud_873391
        - title: 洗手间
          entities:
            - entity: switch.212a01_cloud_873391
        - title: 阳台
          entities:
            - entity: switch.212a01_cloud_873391
              name: 阳台沙发灯

  # ================================================================================================================================================================
  # 网络设备状态
  # Network_Status
  network_status:
    title: 网络&网关
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: false
    subtitle: "[[[ return `路由器当前下行速率为 ${states['sensor.redmi_ac2100_wireless_router_kib_s_received'].state} KiB/s，上行速率为 ${states['sensor.redmi_ac2100_wireless_router_kib_s_sent'].state} KiB/s。`; ]]]"
    columns:
      buttons: 3
    icon: mdi:lan
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default

  # ================================================================================================================================================================
  # 天气预报
  # Weather
  weather:
    title: 天气预报
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: true
    subtitle: "[[[ return `${states['weather.lcde_jia'].state}`; ]]]"
    button_badge: weather.lcde_jia
    columns:
      buttons: 3
    icon: mdi:weather-partly-cloudy
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      weather:
        - title: 天气预报
          type: core
          entity: weather.lcde_jia
          show_forecast: true
          path: weather

  # ================================================================================================================================================================
  # 气候 使用了 sensor传感器 插件
  # Climate
  climate:
    title: 气候
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: false
    subtitle: "[[[ return `当前客厅温度 ${states['sensor.t2_cloud_c0lo00_temperature'].state}°C 当前客厅湿度 ${states['sensor.t2_cloud_c0lo00_humidity'].state}% 当前客厅湿温度计电池电量 ${states['sensor.t2_cloud_c0lo00_level'].state}%` ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:thermometer
    button_badge: sensor.t2_cloud_c0lo00_temperature
    button_label: "[[[ return `温度 ${states['sensor.t2_cloud_c0lo00_temperature'].state}°C 湿度 ${states['sensor.t2_cloud_c0lo00_humidity'].state}%`; ]]]"
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      sensor:
        - title: 客厅
          line_color: red
          columns: 3
          entities:
            - entity: sensor.t2_cloud_c0lo00_temperature
              name: 客厅温度
              line_color: green
            - entity: sensor.t2_cloud_c0lo00_humidity
              name: 客厅湿度
              line_color: blue
            - entity: sensor.t2_cloud_c0lo00_level
              name: 客厅湿温度计电池电量
              line_color: red

  # ================================================================================================================================================================
  # 电池 一些设备的电池电量汇总
  # Battery
  battery:
    title: 电池
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: false
    subtitle: "[[[ return `一些设备的电池电量` ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:battery
    button_badge: sensor.t2_cloud_c0lo00_level
    button_label: "[[[ return `一些设备的电池电量`; ]]]"
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      battery:
        - title: 客厅
          columns: 3
          entities:
            - entity: sensor.t2_cloud_c0lo00_level
              name: 湿温度计电池电量
        - title: LC在上海
          columns: 3
          entities:
            - entity: sensor.theiphoneoflcde_iphone_battery_level
              name: iPhone电池电量
            - entity: sensor.dw2hl_cloud_t85c00_level
              name: 小米门窗传感器 faker门锁

  # ================================================================================================================================================================
  # 摄像头 安全security监控
  # Camera
  security:
    title: 摄像头
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: true
    subtitle: "[[[ return `一些监控设备` ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:cctv
    button_badge: camera.192_168_5_37
    button_label: "[[[ return `一些监控设备`; ]]]"
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      camera:
        - title: 客厅
          aspect_ratio: 16x9 # 默认 16x10
          columns: 3
          entities:
            - entity: camera.192_168_5_37
              # name: 客厅摄像头1 # 这个没有name属性 留着是出于备注的目的
              camera_view: auto
              show_state: true
        - title: LC在上海
          columns: 3
          entities:
            - entity: camera.192_168_5_37
              # name: LC在上海摄像头1
              camera_view: live
              show_state: true
            - entity: camera.192_168_5_37
              # name: LC在上海摄像头2
              camera_view: false # 默认不启用 false 可选 auto | live
              show_state: true

  # ================================================================================================================================================================
  # 门窗传感器 Door and window sensor 监听门窗的开与关
  # Door and window sensor
  DoorAndWindow:
    title: 门窗传感器
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: true
    subtitle: "[[[ return `一些门窗传感器 小提示 如果门窗处于开启的状态 下面的按钮的图标会是已开启的门窗图标 否则是关闭的门窗图标` ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:door
    button_badge: binary_sensor.dw2hl_cloud_t85c00_state # 按钮徽章
    button_label: "[[[ return `一些门窗传感器`; ]]]" # 按钮文本
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      button:
        - title: LC在上海 faker门锁
          entities:
            - entity: binary_sensor.dw2hl_cloud_t85c00_state
              name: faker门锁
              icon: "[[[ if (entity.state == 'on') return `mdi:door`; else return `mdi:door-open`; ]]]"
              # button_label: "[[[ if (entity.state == 'on') return `已关闭`; else return `已打开`; ]]]"
            - entity: sensor.dw2hl_cloud_t85c00_level
              name: faker门锁电池电量
              icon: mdi:battery
              button_label: "[[[ return entity.state; ]]]"
        - title: LC在安徽 窗户锁
          entities:
            - entity: binary_sensor.dw2hl_cloud_t85c00_state
              name: 窗户锁
              icon: "[[[ if (entity.state == 'on') return `mdi:window-closed-variant`; else return `mdi:window-open-variant`; ]]]"
            - entity: sensor.dw2hl_cloud_t85c00_level
              name: 窗户锁电池电量
              icon: mdi:battery
              button_label: "[[[ return entity.state; ]]]"

  # ================================================================================================================================================================
  # 电视控制 红米电视 控制开关机 其实也就是个多媒体插件 目前操作的是 天猫精灵 和电视同理
  # 填入错误的实体 media_player.wo_de_tian_mao_mo_he 其实就是天猫精灵 Android TV =  media_player.android_tv_192_168_5_84
  # TV media 电视 音响 多媒体
  TVs:
    title: 多媒体
    show_in_navbar: false
    show_in_menu: true
    show_in_favorites: true
    subtitle: "[[[ return `一些多媒体 电视 音响 等` ]]]"
    columns:
      buttons: 3
      view_selector: 2
    icon: mdi:youtube-tv # mdi:remote-tv
    button_badge: media_player.android_tv_192_168_5_84 # 按钮徽章
    button_label: "[[[ return `一些多媒体 电视 音响`; ]]]" # 按钮文本
    layout:
      layout_type: custom:horizontal-layout
      options:
        - max_cols: 3
          max_width: 500
          width: 300
    custom_cards:
      position: top
      type: default
    addons:
      remote_control:
        - title: 多媒体远程控制 天猫精灵
          media_player: media_player.android_tv_192_168_5_84
          # sound_player: media_player.l05c_cloud_066435
          sound_player: media_player.android_tv_192_168_5_84
          remote_entity: media_player.android_tv_192_168_5_84
      media_player:
        - type: core
          title: kodi media player in 天猫精灵
          entities:
            - media_player.kodi_in_android_tv

  # ================================================================================================================================================================
  # TODO3
  # 其他待做

  # ================================================================================================================================================================
  # TODO4
  # 其他待做

  # ================================================================================================================================================================